option('truetype', type : 'string',  value : 'freetype', description: 'Library using to render truetype font (freetype,stb)')

option('sdl2',   type : 'boolean', value : false,  description: 'Build the window/events support using SDL2')
option('sdl3',   type : 'boolean', value : false,  description: 'Build the window/events and renderer/GPU support using SDL3')
option('glfw',  type : 'boolean', value : false,  description: 'Build the window/events support using GLFW')
option('win32', type : 'boolean', value : false,  description: 'Build the window/events support using Win32')
option('osx',   type : 'boolean', value : false,  description: 'Build the window/events support using MacOS')

option('opengl2', type : 'boolean', value : false,  description: 'Build the 3D API support using OpenGL2')
option('opengl3', type : 'boolean', value : false,  description: 'Build the 3D API support using OpenGL3')
option('vulkan',  type : 'boolean', value : false,  description: 'Build the 3D API support using Vulkan')
option('d3d9',    type : 'boolean', value : false,  description: 'Build the 3D API support using Direct3D9')
option('d3d10',   type : 'boolean', value : false,  description: 'Build the 3D API support using Direct3D10')
option('d3d11',   type : 'boolean', value : false,  description: 'Build the 3D API support using Direct3D11')
option('d3d12',   type : 'boolean', value : false,  description: 'Build the 3D API support using Direct3D12')
option('metal',   type : 'boolean', value : false,  description: 'Build the 3D API support using Metal')

option('largeidx', type : 'boolean', value : false, description: 'Use 32-bit wide for drawing indices')
option('cimpl',    type : 'boolean', value : false, description: 'Define impl functions as extern "C"')
option('stdlib',   type : 'boolean', value : false, description: 'Add supprt for using C++ strings')
option('gamepad', type : 'boolean', value : false, description: 'Enable gamepad support in SDL3 demo executables')

