option('truetype', type : 'string', value : 'freetype', description: 'Library using to render truetype font (freetype,stb)')
option('sdl', type : 'boolean', value : true,  description: 'Build the window/events support using SDL2')
option('opengl3', type : 'boolean', value : true,  description: 'Build the 3D API support using OpenGL3')
option('largeidx', type : 'boolean', value : false,     description: 'Use 32-bit wide for drawing indices')

